import { rng, shuffle, pick } from './rng';
import { MATHS_TOPICS, MATHS_TRAILS } from './maths-data';

/**
 * Maths questions are generated by "type" instead of from a word list —
 * there's no equivalent of a phonics sound's word bank, just the rules of
 * the skill itself (count objects, compare two numbers, add, subtract...).
 * Every builder below returns the same question shape Question.js already
 * renders, so lesson/practice/quiz pages don't need to know maths exists.
 */

function numberOptions(answer, min, max, next, count = 4) {
  const pool = [];
  for (let n = min; n <= max; n++) if (n !== answer) pool.push(n);
  const distractors = pick(pool, Math.min(count - 1, pool.length), next);
  return shuffle([answer, ...distractors], next).map((n) => ({ id: String(n), label: String(n) }));
}

function buildCountQuestions(skill, { count, seed }) {
  const next = rng(skill.id + ':' + seed);
  const [min, max] = skill.range;
  const out = [];
  for (let i = 0; i < count; i++) {
    const n = Math.floor(next() * (max - min + 1)) + min;
    const icon = skill.icons[Math.floor(next() * skill.icons.length)];
    out.push({
      id: `q-count-${i}`,
      kind: 'count',
      prompt: 'How many are there?',
      grid: Array.from({ length: n }, () => icon),
      options: numberOptions(n, min, max, next),
      answer: String(n),
      hint: 'Point to each one and count out loud.',
    });
  }
  return out;
}

function buildCompareQuestions(skill, { count, seed }) {
  const next = rng(skill.id + ':' + seed);
  const [min, max] = skill.range;
  const out = [];
  for (let i = 0; i < count; i++) {
    const a = Math.floor(next() * (max - min + 1)) + min;
    let b = Math.floor(next() * (max - min + 1)) + min;
    if (b === a) b = a === max ? a - 1 : a + 1;
    const askBigger = next() > 0.5;
    const answer = askBigger ? Math.max(a, b) : Math.min(a, b);
    out.push({
      id: `q-compare-${i}`,
      kind: 'compare',
      prompt: askBigger ? 'Which number is bigger?' : 'Which number is smaller?',
      options: shuffle([a, b], next).map((n) => ({ id: String(n), label: String(n) })),
      answer: String(answer),
      hint: askBigger ? 'The bigger number counts further.' : 'The smaller number counts less far.',
    });
  }
  return out;
}

function buildShapeQuestions(skill, { count, seed }) {
  const next = rng(skill.id + ':' + seed);
  const shapes = skill.shapes;
  const out = [];
  for (let i = 0; i < count; i++) {
    const target = shapes[Math.floor(next() * shapes.length)];
    const distractors = pick(
      shapes.filter((s) => s.name !== target.name),
      3,
      next
    );
    out.push({
      id: `q-shape-${i}`,
      kind: 'shape',
      prompt: `Which one is the ${target.name.toLowerCase()}?`,
      options: shuffle([target, ...distractors], next).map((s) => ({
        id: s.name,
        label: s.name,
        emoji: s.emoji,
      })),
      answer: target.name,
      hint: `Look for the ${target.name.toLowerCase()} shape.`,
    });
  }
  return out;
}

function buildAdditionQuestions(skill, { count, seed }) {
  const next = rng(skill.id + ':' + seed);
  const out = [];
  for (let i = 0; i < count; i++) {
    const a = Math.floor(next() * 9) + 1; // 1..9
    const b = Math.floor(next() * (10 - a)) + 1; // keeps the sum at 10 or under
    const sum = a + b;
    out.push({
      id: `q-add-${i}`,
      kind: 'sum',
      prompt: `What is ${a} + ${b}?`,
      show: '➕',
      showWord: `${a} + ${b} = ?`,
      options: numberOptions(sum, 0, 10, next),
      answer: String(sum),
      hint: `Start at ${a} and count on ${b} more.`,
    });
  }
  return out;
}

function buildSubtractionQuestions(skill, { count, seed }) {
  const next = rng(skill.id + ':' + seed);
  const out = [];
  for (let i = 0; i < count; i++) {
    const a = Math.floor(next() * 9) + 2; // 2..10
    const b = Math.floor(next() * (a - 1)) + 1; // 1..a-1, keeps a positive answer
    const diff = a - b;
    out.push({
      id: `q-sub-${i}`,
      kind: 'sum',
      prompt: `What is ${a} − ${b}?`,
      show: '➖',
      showWord: `${a} − ${b} = ?`,
      options: numberOptions(diff, 0, 10, next),
      answer: String(diff),
      hint: `Start at ${a} and count back ${b}.`,
    });
  }
  return out;
}

function buildBondsQuestions(skill, { count, seed }) {
  const next = rng(skill.id + ':' + seed);
  const out = [];
  for (let i = 0; i < count; i++) {
    const a = Math.floor(next() * 9) + 1; // 1..9
    const b = 10 - a;
    out.push({
      id: `q-bond-${i}`,
      kind: 'sum',
      prompt: `${a} and what makes 10?`,
      show: '🔟',
      showWord: `${a} + ? = 10`,
      options: numberOptions(b, 0, 10, next),
      answer: String(b),
      hint: `Count up from ${a} until you reach 10.`,
    });
  }
  return out;
}

const BUILDERS = {
  count: buildCountQuestions,
  compare: buildCompareQuestions,
  shape: buildShapeQuestions,
  addition: buildAdditionQuestions,
  subtraction: buildSubtractionQuestions,
  bonds: buildBondsQuestions,
};

function buildMathsQuestions(skill, opts) {
  const builder = BUILDERS[skill.type];
  return builder ? builder(skill, opts) : [];
}

function buildMathsLesson(skill) {
  return {
    intro: skill.intro,
    chant: skill.chant,
    example: buildMathsQuestions(skill, { count: 1, seed: 'example' })[0] || null,
  };
}

function buildMathsTopic(skill) {
  return {
    id: skill.id,
    subject: skill.subject,
    trail: skill.trail,
    trailName: MATHS_TRAILS.find((t) => t.id === skill.trail)?.name || '',
    kind: 'maths',
    display: skill.display,
    name: skill.name,
    sound: '',
    grade: skill.grade,
    lesson: buildMathsLesson(skill),
    practice: buildMathsQuestions(skill, { count: 5, seed: 'practice' }),
    quiz: buildMathsQuestions(skill, { count: 5, seed: 'quiz' }),
  };
}

export const MATHS_CORE_TOPICS = MATHS_TOPICS.map(buildMathsTopic);
export { MATHS_TRAILS };
