/**
 * Raw phonics content.
 *
 * Each entry is one "sound" that becomes a full topic (lesson + practice + quiz).
 * Keeping it as plain data means a grown-up (or the AI studio) can add more
 * without touching any app logic.
 *
 * Fields:
 *  id        unique slug, used in URLs
 *  display   the letter(s) the child sees on the big tile
 *  name      friendly topic name
 *  sound     written form of the sound, e.g. /a/
 *  say       a spelling the phone's voice can read out loud as the *sound*
 *            (voices read "b" as "bee", so we feed it "buh")
 *  mouth     what the child's mouth/lips/tongue do
 *  chant     a short rhythm line to say together
 *  position  'start' (default) or 'end' — where the sound sits in the words
 *  words     "word|emoji" pairs
 */

const w = (s) =>
  s
    .trim()
    .split(/\s+/)
    .map((pair) => {
      const [word, emoji] = pair.split('|');
      return { word, emoji: emoji || '✨' };
    });

export const TRAILS = [
  {
    id: 'short-vowels',
    name: 'Short Vowel Trail',
    blurb: 'The five little vowel sounds that start almost every word.',
    emoji: '🌿',
    color: 'leaf',
  },
  {
    id: 'consonants-1',
    name: 'Consonant Camp: B to M',
    blurb: 'First half of the alphabet sounds.',
    emoji: '⛺',
    color: 'sky',
  },
  {
    id: 'consonants-2',
    name: 'Consonant Camp: N to Z',
    blurb: 'Second half of the alphabet sounds.',
    emoji: '🏕️',
    color: 'grape',
  },
  {
    id: 'long-vowels',
    name: 'Long Vowel Lagoon',
    blurb: 'When a vowel says its own name.',
    emoji: '🏝️',
    color: 'coral',
  },
  {
    id: 'digraphs',
    name: 'Two-Letter Team-Ups',
    blurb: 'Two letters, one brand new sound.',
    emoji: '🤝',
    color: 'mango',
  },
];

export const SOUNDS = [
  // ── Short vowels ───────────────────────────────────────────────────────────
  {
    id: 'short-a',
    trail: 'short-vowels',
    display: 'a',
    name: 'Short A',
    sound: '/a/',
    say: 'ah',
    mouth: 'Open your mouth wide like a hungry hippo and say "ah".',
    chant: 'a — a — ah! The cat sat on my hat!',
    words: w('cat|🐱 hat|🎩 bag|👜 map|🗺️ jam|🍓 van|🚐'),
  },
  {
    id: 'short-e',
    trail: 'short-vowels',
    display: 'e',
    name: 'Short E',
    sound: '/e/',
    say: 'eh',
    mouth: 'Smile a little and say "eh", like you did not quite hear someone.',
    chant: 'e — e — eh! Ten hens in a nest!',
    words: w('bed|🛏️ pen|🖊️ hen|🐔 net|🥅 leg|🦵 ten|🔟'),
  },
  {
    id: 'short-i',
    trail: 'short-vowels',
    display: 'i',
    name: 'Short I',
    sound: '/i/',
    say: 'ih',
    mouth: 'Tiny smile, tongue up high, say a quick "ih".',
    chant: 'i — i — ih! A pig did a big jig!',
    words: w('pig|🐷 lip|👄 six|6️⃣ fish|🐟 zip|🤐 pin|📌'),
  },
  {
    id: 'short-o',
    trail: 'short-vowels',
    display: 'o',
    name: 'Short O',
    sound: '/o/',
    say: 'awe',
    mouth: 'Round lips like a doughnut and say "o".',
    chant: 'o — o — ah! A fox in a box!',
    words: w('dog|🐶 box|📦 fox|🦊 mop|🧹 pot|🍲 log|🪵'),
  },
  {
    id: 'short-u',
    trail: 'short-vowels',
    display: 'u',
    name: 'Short U',
    sound: '/u/',
    say: 'uh',
    mouth: 'Relax your mouth and grunt a short "uh".',
    chant: 'u — u — uh! A bug in a cup!',
    words: w('sun|☀️ bug|🐛 cup|☕ bus|🚌 duck|🦆 rug|🧶'),
  },

  // ── Consonants B–M ─────────────────────────────────────────────────────────
  {
    id: 'sound-b',
    trail: 'consonants-1',
    display: 'b',
    name: 'The B Sound',
    sound: '/b/',
    say: 'buh',
    mouth: 'Press your lips together, then pop them open: "b".',
    chant: 'b, b, b — a big blue ball for me!',
    words: w('ball|⚽ bus|🚌 bed|🛏️ book|📕 bug|🐛 bat|🦇'),
  },
  {
    id: 'sound-c',
    trail: 'consonants-1',
    display: 'c',
    name: 'The C Sound',
    sound: '/k/',
    say: 'kuh',
    mouth: 'Click the back of your tongue: "c".',
    chant: 'c, c, c — a cup of cocoa for me!',
    words: w('cat|🐱 cup|☕ car|🚗 cow|🐄 cake|🎂 cap|🧢'),
  },
  {
    id: 'sound-d',
    trail: 'consonants-1',
    display: 'd',
    name: 'The D Sound',
    sound: '/d/',
    say: 'duh',
    mouth: 'Tap your tongue behind your top teeth: "d".',
    chant: 'd, d, d — a duck and a dog and me!',
    words: w('dog|🐶 duck|🦆 doll|🪆 desk|🪑 dish|🍽️ door|🚪'),
  },
  {
    id: 'sound-f',
    trail: 'consonants-1',
    display: 'f',
    name: 'The F Sound',
    sound: '/f/',
    say: 'fff',
    mouth: 'Top teeth on your bottom lip and blow softly: "ffff".',
    chant: 'f, f, f — a fish and a frog and a fan!',
    words: w('fish|🐟 fan|🪭 fox|🦊 frog|🐸 foot|🦶 fire|🔥'),
  },
  {
    id: 'sound-g',
    trail: 'consonants-1',
    display: 'g',
    name: 'The G Sound',
    sound: '/g/',
    say: 'guh',
    mouth: 'Back of the tongue again, but switch your voice on: "g".',
    chant: 'g, g, g — a goat at the garden gate!',
    words: w('goat|🐐 gate|🚧 gift|🎁 gum|🍬 girl|👧 grapes|🍇'),
  },
  {
    id: 'sound-h',
    trail: 'consonants-1',
    display: 'h',
    name: 'The H Sound',
    sound: '/h/',
    say: 'hh',
    mouth: 'Breathe out like you are fogging a window: "h".',
    chant: 'h, h, h — a horse and a hat and a hug!',
    words: w('hat|🎩 hen|🐔 horse|🐴 house|🏠 hug|🤗 hand|✋'),
  },
  {
    id: 'sound-j',
    trail: 'consonants-1',
    display: 'j',
    name: 'The J Sound',
    sound: '/j/',
    say: 'juh',
    mouth: 'Push your lips forward and say "j", like a jumping jelly.',
    chant: 'j, j, j — jam on my toast today!',
    words: w('jam|🍓 jet|✈️ jug|🏺 juice|🧃 jump|🤸 jar|🫙'),
  },
  {
    id: 'sound-k',
    trail: 'consonants-1',
    display: 'k',
    name: 'The K Sound',
    sound: '/k/',
    say: 'kuh',
    mouth: 'Same click as c — k and c are sound twins!',
    chant: 'k, k, k — a kite flew far away!',
    words: w('kite|🪁 key|🔑 king|🤴 kid|🧒 kitten|🐈 koala|🐨'),
  },
  {
    id: 'sound-l',
    trail: 'consonants-1',
    display: 'l',
    name: 'The L Sound',
    sound: '/l/',
    say: 'llll',
    mouth: 'Tongue tip up behind your teeth and hum: "llll".',
    chant: 'l, l, l — a lion with a lemon!',
    words: w('lion|🦁 leg|🦵 leaf|🍃 lamp|💡 lemon|🍋 log|🪵'),
  },
  {
    id: 'sound-m',
    trail: 'consonants-1',
    display: 'm',
    name: 'The M Sound',
    sound: '/m/',
    say: 'mmm',
    mouth: 'Lips closed, hum like something tastes yummy: "mmm".',
    chant: 'm, m, m — the moon and my mango!',
    words: w('moon|🌙 map|🗺️ milk|🥛 mouse|🐭 mango|🥭 mop|🧹'),
  },

  // ── Consonants N–Z ─────────────────────────────────────────────────────────
  {
    id: 'sound-n',
    trail: 'consonants-2',
    display: 'n',
    name: 'The N Sound',
    sound: '/n/',
    say: 'nnn',
    mouth: 'Tongue up, hum through your nose: "nnn".',
    chant: 'n, n, n — a nest with nine eggs in!',
    words: w('nest|🪹 nose|👃 net|🥅 nut|🥜 nine|9️⃣ nurse|👩‍⚕️'),
  },
  {
    id: 'sound-p',
    trail: 'consonants-2',
    display: 'p',
    name: 'The P Sound',
    sound: '/p/',
    say: 'puh',
    mouth: 'Pop your lips with a puff of air: "p". No voice!',
    chant: 'p, p, p — a pig in a purple park!',
    words: w('pig|🐷 pen|🖊️ pot|🍲 pan|🍳 pin|📌 park|🏞️'),
  },
  {
    id: 'sound-qu',
    trail: 'consonants-2',
    display: 'qu',
    name: 'The Qu Sound',
    sound: '/kw/',
    say: 'kwuh',
    mouth: 'q always brings u along. Together they say "kw".',
    chant: 'qu, qu, qu — the quick queen said quack!',
    words: w('queen|👑 quilt|🧵 quiz|❓ quick|⚡ duck|🦆 quiet|🤫'),
  },
  {
    id: 'sound-r',
    trail: 'consonants-2',
    display: 'r',
    name: 'The R Sound',
    sound: '/r/',
    say: 'rrr',
    mouth: 'Curl your tongue back and growl: "rrr".',
    chant: 'r, r, r — rain on the red rock!',
    words: w('rain|🌧️ rat|🐀 rock|🪨 rope|🪢 ring|💍 robot|🤖'),
  },
  {
    id: 'sound-s',
    trail: 'consonants-2',
    display: 's',
    name: 'The S Sound',
    sound: '/s/',
    say: 'sss',
    mouth: 'Teeth together and hiss like a snake: "ssss".',
    chant: 's, s, s — the sun on the sea!',
    words: w('sun|☀️ sock|🧦 seal|🦭 star|⭐ snake|🐍 soup|🍜'),
  },
  {
    id: 'sound-t',
    trail: 'consonants-2',
    display: 't',
    name: 'The T Sound',
    sound: '/t/',
    say: 'tuh',
    mouth: 'Tap your tongue and puff: "t". Like a tiny drum.',
    chant: 't, t, t — a tiger in a tent!',
    words: w('tiger|🐯 tent|⛺ top|🔝 tub|🛁 ten|🔟 tree|🌳'),
  },
  {
    id: 'sound-v',
    trail: 'consonants-2',
    display: 'v',
    name: 'The V Sound',
    sound: '/v/',
    say: 'vvv',
    mouth: 'Like f, but buzzy — feel your lip tickle: "vvv".',
    chant: 'v, v, v — a van by the volcano!',
    words: w('van|🚐 vet|🩺 vase|🏺 violin|🎻 volcano|🌋 vest|🦺'),
  },
  {
    id: 'sound-w',
    trail: 'consonants-2',
    display: 'w',
    name: 'The W Sound',
    sound: '/w/',
    say: 'wuh',
    mouth: 'Round your lips tight then open: "w".',
    chant: 'w, w, w — a web on the window!',
    words: w('web|🕸️ water|💧 wall|🧱 window|🪟 wolf|🐺 watch|⌚'),
  },
  {
    id: 'sound-x',
    trail: 'consonants-2',
    display: 'x',
    name: 'The X Sound',
    sound: '/ks/',
    say: 'ks',
    mouth: 'x hides at the END of words and says "ks".',
    chant: 'x, x, x — a fox in a box with six!',
    position: 'end',
    words: w('box|📦 fox|🦊 six|6️⃣ mix|🥣 fix|🔧 wax|🕯️'),
  },
  {
    id: 'sound-y',
    trail: 'consonants-2',
    display: 'y',
    name: 'The Y Sound',
    sound: '/y/',
    say: 'yuh',
    mouth: 'Smile and push the sound out: "y", like saying yes.',
    chant: 'y, y, y — yellow yarn and yum!',
    words: w('yak|🐃 yarn|🧶 yo-yo|🪀 yogurt|🥣 yellow|💛 yard|🌳'),
  },
  {
    id: 'sound-z',
    trail: 'consonants-2',
    display: 'z',
    name: 'The Z Sound',
    sound: '/z/',
    say: 'zzz',
    mouth: 'Buzz like a sleepy bee: "zzzz".',
    chant: 'z, z, z — a zebra at the zoo!',
    words: w('zebra|🦓 zoo|🦁 zip|🤐 zero|0️⃣ zigzag|⚡ zone|🚧'),
  },

  // ── Long vowels ────────────────────────────────────────────────────────────
  {
    id: 'long-a',
    trail: 'long-vowels',
    display: 'a_e',
    name: 'Long A',
    sound: '/ai/',
    say: 'ay',
    mouth: 'The a says its own name: "ay". A silent e at the end does the magic.',
    chant: 'a — e — ay! Bake a cake today!',
    words: w('cake|🎂 gate|🚧 snake|🐍 rain|🌧️ tape|📼 train|🚂'),
  },
  {
    id: 'long-e',
    trail: 'long-vowels',
    display: 'ee',
    name: 'Long E',
    sound: '/ee/',
    say: 'ee',
    mouth: 'Big smile and squeeze out "eee", like a happy mouse.',
    chant: 'e — e — ee! A bee in a tree!',
    words: w('bee|🐝 tree|🌳 feet|🦶 sheep|🐑 queen|👑 green|🟢'),
  },
  {
    id: 'long-i',
    trail: 'long-vowels',
    display: 'i_e',
    name: 'Long I',
    sound: '/ie/',
    say: 'eye',
    mouth: 'The i says its own name: "eye".',
    chant: 'i — e — eye! A kite in the sky!',
    words: w('kite|🪁 bike|🚲 nine|9️⃣ smile|😀 slide|🛝 fire|🔥'),
  },
  {
    id: 'long-o',
    trail: 'long-vowels',
    display: 'o_e',
    name: 'Long O',
    sound: '/oa/',
    say: 'oh',
    mouth: 'Round lips and say "oh", like you just got a surprise.',
    chant: 'o — e — oh! A boat where the rivers go!',
    words: w('bone|🦴 rope|🪢 home|🏠 boat|⛵ globe|🌍 nose|👃'),
  },
  {
    id: 'long-u',
    trail: 'long-vowels',
    display: 'u_e',
    name: 'Long U',
    sound: '/ue/',
    say: 'you',
    mouth: 'The u says its own name: "yoo".',
    chant: 'u — e — you! A mule and a flute for two!',
    words: w('cube|🧊 mule|🐴 flute|🎶 tube|🧻 unicorn|🦄 music|🎵'),
  },

  // ── Digraphs ───────────────────────────────────────────────────────────────
  {
    id: 'digraph-sh',
    trail: 'digraphs',
    display: 'sh',
    name: 'Sh Together',
    sound: '/sh/',
    say: 'shh',
    mouth: 'Finger on your lips: "shhh", quiet like a library.',
    chant: 'sh, sh, sh — a shell and a shiny fish!',
    words: w('ship|🚢 shell|🐚 shark|🦈 shop|🏪 sheep|🐑 shoe|👟'),
  },
  {
    id: 'digraph-ch',
    trail: 'digraphs',
    display: 'ch',
    name: 'Ch Together',
    sound: '/ch/',
    say: 'ch',
    mouth: 'Chug like a little train: "ch, ch, ch".',
    chant: 'ch, ch, ch — cheese on my chair!',
    words: w('chair|🪑 cheese|🧀 chick|🐤 chips|🍟 cherry|🍒 chin|😀'),
  },
  {
    id: 'digraph-th',
    trail: 'digraphs',
    display: 'th',
    name: 'Th Together',
    sound: '/th/',
    say: 'th',
    mouth: 'Poke your tongue between your teeth and blow: "th".',
    chant: 'th, th, th — three thumbs up!',
    words: w('thumb|👍 three|3️⃣ think|💭 thorn|🌹 bath|🛁 moth|🦋'),
  },
  {
    id: 'digraph-ng',
    trail: 'digraphs',
    display: 'ng',
    name: 'Ng Together',
    sound: '/ng/',
    say: 'ng',
    mouth: 'Hum at the back of your throat: "ng". It lives at the end of words.',
    chant: 'ng, ng, ng — a king likes to sing!',
    position: 'end',
    words: w('ring|💍 king|🤴 song|🎵 wing|🪽 swing|🛝 strong|💪'),
  },
  {
    id: 'digraph-ck',
    trail: 'digraphs',
    display: 'ck',
    name: 'Ck Together',
    sound: '/k/',
    say: 'kuh',
    mouth: 'c and k hold hands at the end of short words and say "k".',
    chant: 'ck, ck, ck — a duck on a rock!',
    position: 'end',
    words: w('duck|🦆 sock|🧦 rock|🪨 clock|🕐 truck|🚚 lock|🔒'),
  },
];
